# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DNDMapper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DNDMapper.proto',
  package='DNDProto',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x44NDMapper.proto\x12\x08\x44NDProto\"_\n\x05Token\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\x05\x12\x0c\n\x04posX\x18\x03 \x01(\x02\x12\x0c\n\x04posY\x18\x04 \x01(\x02\x12\n\n\x02id\x18\x05 \x02(\x05\x12\x11\n\tisDestroy\x18\x06 \x01(\x08\"c\n\x03Map\x12\r\n\x05sizeX\x18\x01 \x02(\x05\x12\r\n\x05sizeY\x18\x02 \x02(\x05\x12\r\n\x05tiles\x18\x03 \x03(\x05\x12\x0e\n\x06\x66ogged\x18\x04 \x03(\x08\x12\x1f\n\x06tokens\x18\x05 \x03(\x0b\x32\x0f.DNDProto.Token\"M\n\nTileUpdate\x12\x0c\n\x04posX\x18\x01 \x02(\x02\x12\x0c\n\x04posY\x18\x02 \x02(\x02\x12\x10\n\x08newColor\x18\x03 \x01(\x05\x12\x11\n\tnewFogged\x18\x04 \x01(\x08\"\xee\x02\n\x0eNetworkMessage\x12\x39\n\x0bmessageType\x18\x01 \x02(\x0e\x32$.DNDProto.NetworkMessage.MessageType\x12\x1a\n\x03map\x18\x02 \x01(\x0b\x32\r.DNDProto.Map\x12(\n\ntileUpdate\x18\x03 \x01(\x0b\x32\x14.DNDProto.TileUpdate\x12\x0e\n\x06gameID\x18\x04 \x01(\x05\x12$\n\x0btokenUpdate\x18\x05 \x01(\x0b\x32\x0f.DNDProto.Token\x12\x31\n\x05\x65rror\x18\x06 \x01(\x0e\x32\".DNDProto.NetworkMessage.ErrorType\"&\n\tErrorType\x12\x19\n\x15GameDoesNotExistError\x10\x01\"J\n\x0bMessageType\x12\x0e\n\nCreateGame\x10\x01\x12\x0c\n\x08JoinGame\x10\x02\x12\n\n\x06Update\x10\x03\x12\x06\n\x02ID\x10\x04\x12\t\n\x05\x45rror\x10\x05'
)



_NETWORKMESSAGE_ERRORTYPE = _descriptor.EnumDescriptor(
  name='ErrorType',
  full_name='DNDProto.NetworkMessage.ErrorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GameDoesNotExistError', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=559,
  serialized_end=597,
)
_sym_db.RegisterEnumDescriptor(_NETWORKMESSAGE_ERRORTYPE)

_NETWORKMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='DNDProto.NetworkMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CreateGame', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JoinGame', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Update', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ID', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Error', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=599,
  serialized_end=673,
)
_sym_db.RegisterEnumDescriptor(_NETWORKMESSAGE_MESSAGETYPE)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='DNDProto.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DNDProto.Token.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='DNDProto.Token.color', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='posX', full_name='DNDProto.Token.posX', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='posY', full_name='DNDProto.Token.posY', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='DNDProto.Token.id', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isDestroy', full_name='DNDProto.Token.isDestroy', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=124,
)


_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='DNDProto.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sizeX', full_name='DNDProto.Map.sizeX', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sizeY', full_name='DNDProto.Map.sizeY', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='DNDProto.Map.tiles', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fogged', full_name='DNDProto.Map.fogged', index=3,
      number=4, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='DNDProto.Map.tokens', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=225,
)


_TILEUPDATE = _descriptor.Descriptor(
  name='TileUpdate',
  full_name='DNDProto.TileUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='posX', full_name='DNDProto.TileUpdate.posX', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='posY', full_name='DNDProto.TileUpdate.posY', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newColor', full_name='DNDProto.TileUpdate.newColor', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newFogged', full_name='DNDProto.TileUpdate.newFogged', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=304,
)


_NETWORKMESSAGE = _descriptor.Descriptor(
  name='NetworkMessage',
  full_name='DNDProto.NetworkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='DNDProto.NetworkMessage.messageType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map', full_name='DNDProto.NetworkMessage.map', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tileUpdate', full_name='DNDProto.NetworkMessage.tileUpdate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameID', full_name='DNDProto.NetworkMessage.gameID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokenUpdate', full_name='DNDProto.NetworkMessage.tokenUpdate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='DNDProto.NetworkMessage.error', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NETWORKMESSAGE_ERRORTYPE,
    _NETWORKMESSAGE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=673,
)

_MAP.fields_by_name['tokens'].message_type = _TOKEN
_NETWORKMESSAGE.fields_by_name['messageType'].enum_type = _NETWORKMESSAGE_MESSAGETYPE
_NETWORKMESSAGE.fields_by_name['map'].message_type = _MAP
_NETWORKMESSAGE.fields_by_name['tileUpdate'].message_type = _TILEUPDATE
_NETWORKMESSAGE.fields_by_name['tokenUpdate'].message_type = _TOKEN
_NETWORKMESSAGE.fields_by_name['error'].enum_type = _NETWORKMESSAGE_ERRORTYPE
_NETWORKMESSAGE_ERRORTYPE.containing_type = _NETWORKMESSAGE
_NETWORKMESSAGE_MESSAGETYPE.containing_type = _NETWORKMESSAGE
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
DESCRIPTOR.message_types_by_name['Map'] = _MAP
DESCRIPTOR.message_types_by_name['TileUpdate'] = _TILEUPDATE
DESCRIPTOR.message_types_by_name['NetworkMessage'] = _NETWORKMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'DNDMapper_pb2'
  # @@protoc_insertion_point(class_scope:DNDProto.Token)
  })
_sym_db.RegisterMessage(Token)

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), {
  'DESCRIPTOR' : _MAP,
  '__module__' : 'DNDMapper_pb2'
  # @@protoc_insertion_point(class_scope:DNDProto.Map)
  })
_sym_db.RegisterMessage(Map)

TileUpdate = _reflection.GeneratedProtocolMessageType('TileUpdate', (_message.Message,), {
  'DESCRIPTOR' : _TILEUPDATE,
  '__module__' : 'DNDMapper_pb2'
  # @@protoc_insertion_point(class_scope:DNDProto.TileUpdate)
  })
_sym_db.RegisterMessage(TileUpdate)

NetworkMessage = _reflection.GeneratedProtocolMessageType('NetworkMessage', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKMESSAGE,
  '__module__' : 'DNDMapper_pb2'
  # @@protoc_insertion_point(class_scope:DNDProto.NetworkMessage)
  })
_sym_db.RegisterMessage(NetworkMessage)


# @@protoc_insertion_point(module_scope)
